[package]
name = "shannon"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]

[dependencies.shannon-sys]
path = "shannon-sys"
version = "0.1.0"

[dependencies]
byteorder = "*"

[dependencies.readall]
git = "https://github.com/plietar/rust-readall.git"

